version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: ai_starter-postgres
    command: ["postgres", "-c", "wal_level=logical"]
    environment:
      POSTGRES_DB: ai_starter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
