/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/0xcadams/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "../db/schema";
import type { DrizzleToZeroSchema } from "drizzle-zero";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    account: {
      name: "account",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "id"
          >,
        },
        accountId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "accountId"
          >,
          serverName: "account_id",
        },
        providerId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "providerId"
          >,
          serverName: "provider_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "userId"
          >,
          serverName: "user_id",
        },
        accessToken: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "accessToken"
          >,
          serverName: "access_token",
        },
        refreshToken: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "refreshToken"
          >,
          serverName: "refresh_token",
        },
        idToken: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "idToken"
          >,
          serverName: "id_token",
        },
        accessTokenExpiresAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "accessTokenExpiresAt"
          >,
          serverName: "access_token_expires_at",
        },
        refreshTokenExpiresAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "refreshTokenExpiresAt"
          >,
          serverName: "refresh_token_expires_at",
        },
        scope: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "scope"
          >,
        },
        password: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "password"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "account",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    issue: {
      name: "issue",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "id"
          >,
        },
        number: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "number"
          >,
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "title"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "description"
          >,
        },
        statusId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "statusId"
          >,
          serverName: "status_id",
        },
        priorityId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "priorityId"
          >,
          serverName: "priority_id",
        },
        projectId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "projectId"
          >,
          serverName: "project_id",
        },
        teamId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "teamId"
          >,
          serverName: "team_id",
        },
        creatorId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "creatorId"
          >,
          serverName: "creator_id",
        },
        assigneeId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "assigneeId"
          >,
          serverName: "assignee_id",
        },
        estimate: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "estimate"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        completedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "completedAt"
          >,
          serverName: "completed_at",
        },
        canceledAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issue",
            "canceledAt"
          >,
          serverName: "canceled_at",
        },
      },
      primaryKey: ["id"],
    },
    issueComment: {
      name: "issueComment",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueComment",
            "id"
          >,
        },
        body: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueComment",
            "body"
          >,
        },
        issueId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueComment",
            "issueId"
          >,
          serverName: "issue_id",
        },
        authorId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueComment",
            "authorId"
          >,
          serverName: "author_id",
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueComment",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueComment",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "issue_comment",
    },
    issueLabel: {
      name: "issueLabel",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueLabel",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueLabel",
            "name"
          >,
        },
        color: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueLabel",
            "color"
          >,
        },
        teamId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueLabel",
            "teamId"
          >,
          serverName: "team_id",
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueLabel",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
      serverName: "issue_label",
    },
    issueLabelAssignment: {
      name: "issueLabelAssignment",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueLabelAssignment",
            "id"
          >,
        },
        issueId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueLabelAssignment",
            "issueId"
          >,
          serverName: "issue_id",
        },
        labelId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueLabelAssignment",
            "labelId"
          >,
          serverName: "label_id",
        },
      },
      primaryKey: ["id"],
      serverName: "issue_label_assignment",
    },
    issuePriority: {
      name: "issuePriority",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issuePriority",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issuePriority",
            "name"
          >,
        },
        value: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issuePriority",
            "value"
          >,
        },
        teamId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issuePriority",
            "teamId"
          >,
          serverName: "team_id",
        },
      },
      primaryKey: ["id"],
      serverName: "issue_priority",
    },
    issueStatus: {
      name: "issueStatus",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueStatus",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueStatus",
            "name"
          >,
        },
        type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueStatus",
            "type"
          >,
        },
        position: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueStatus",
            "position"
          >,
        },
        teamId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueStatus",
            "teamId"
          >,
          serverName: "team_id",
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "issueStatus",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
      serverName: "issue_status",
    },
    project: {
      name: "project",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "name"
          >,
        },
        identifier: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "identifier"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "description"
          >,
        },
        teamId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "teamId"
          >,
          serverName: "team_id",
        },
        leadId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "leadId"
          >,
          serverName: "lead_id",
        },
        startDate: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "startDate"
          >,
          serverName: "start_date",
        },
        targetDate: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "targetDate"
          >,
          serverName: "target_date",
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "project",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    session: {
      name: "session",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "session",
            "id"
          >,
        },
        expiresAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "session",
            "expiresAt"
          >,
          serverName: "expires_at",
        },
        token: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "session",
            "token"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "session",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "session",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
        ipAddress: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "session",
            "ipAddress"
          >,
          serverName: "ip_address",
        },
        userAgent: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "session",
            "userAgent"
          >,
          serverName: "user_agent",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "session",
            "userId"
          >,
          serverName: "user_id",
        },
      },
      primaryKey: ["id"],
    },
    team: {
      name: "team",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "team",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "team",
            "name"
          >,
        },
        identifier: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "team",
            "identifier"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "team",
            "description"
          >,
        },
        image: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "team",
            "image"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "team",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "team",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    teamMember: {
      name: "teamMember",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMember",
            "id"
          >,
        },
        teamId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMember",
            "teamId"
          >,
          serverName: "team_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMember",
            "userId"
          >,
          serverName: "user_id",
        },
        role: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMember",
            "role"
          >,
        },
        joinedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "teamMember",
            "joinedAt"
          >,
          serverName: "joined_at",
        },
      },
      primaryKey: ["id"],
      serverName: "team_member",
    },
    user: {
      name: "user",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "user",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "user",
            "name"
          >,
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "user",
            "email"
          >,
        },
        emailVerified: {
          type: "boolean",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "user",
            "emailVerified"
          >,
          serverName: "email_verified",
        },
        image: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "user",
            "image"
          >,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "user",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "user",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    verification: {
      name: "verification",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verification",
            "id"
          >,
        },
        identifier: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verification",
            "identifier"
          >,
        },
        value: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verification",
            "value"
          >,
        },
        expiresAt: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verification",
            "expiresAt"
          >,
          serverName: "expires_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verification",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "verification",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {
    account: {
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
    },
    issueComment: {
      issue: [
        {
          sourceField: ["issueId"],
          destField: ["id"],
          destSchema: "issue",
          cardinality: "one",
        },
      ],
      author: [
        {
          sourceField: ["authorId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
    },
    issueLabelAssignment: {
      issue: [
        {
          sourceField: ["issueId"],
          destField: ["id"],
          destSchema: "issue",
          cardinality: "one",
        },
      ],
      label: [
        {
          sourceField: ["labelId"],
          destField: ["id"],
          destSchema: "issueLabel",
          cardinality: "one",
        },
      ],
    },
    issueLabel: {
      team: [
        {
          sourceField: ["teamId"],
          destField: ["id"],
          destSchema: "team",
          cardinality: "one",
        },
      ],
      assignments: [
        {
          sourceField: ["id"],
          destField: ["labelId"],
          destSchema: "issueLabelAssignment",
          cardinality: "many",
        },
      ],
    },
    issuePriority: {
      team: [
        {
          sourceField: ["teamId"],
          destField: ["id"],
          destSchema: "team",
          cardinality: "one",
        },
      ],
      issues: [
        {
          sourceField: ["id"],
          destField: ["priorityId"],
          destSchema: "issue",
          cardinality: "many",
        },
      ],
    },
    issue: {
      status: [
        {
          sourceField: ["statusId"],
          destField: ["id"],
          destSchema: "issueStatus",
          cardinality: "one",
        },
      ],
      priority: [
        {
          sourceField: ["priorityId"],
          destField: ["id"],
          destSchema: "issuePriority",
          cardinality: "one",
        },
      ],
      project: [
        {
          sourceField: ["projectId"],
          destField: ["id"],
          destSchema: "project",
          cardinality: "one",
        },
      ],
      team: [
        {
          sourceField: ["teamId"],
          destField: ["id"],
          destSchema: "team",
          cardinality: "one",
        },
      ],
      creator: [
        {
          sourceField: ["creatorId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
      assignee: [
        {
          sourceField: ["assigneeId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
      comments: [
        {
          sourceField: ["id"],
          destField: ["issueId"],
          destSchema: "issueComment",
          cardinality: "many",
        },
      ],
      labelAssignments: [
        {
          sourceField: ["id"],
          destField: ["issueId"],
          destSchema: "issueLabelAssignment",
          cardinality: "many",
        },
      ],
    },
    issueStatus: {
      team: [
        {
          sourceField: ["teamId"],
          destField: ["id"],
          destSchema: "team",
          cardinality: "one",
        },
      ],
      issues: [
        {
          sourceField: ["id"],
          destField: ["statusId"],
          destSchema: "issue",
          cardinality: "many",
        },
      ],
    },
    project: {
      team: [
        {
          sourceField: ["teamId"],
          destField: ["id"],
          destSchema: "team",
          cardinality: "one",
        },
      ],
      lead: [
        {
          sourceField: ["leadId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
      issues: [
        {
          sourceField: ["id"],
          destField: ["projectId"],
          destSchema: "issue",
          cardinality: "many",
        },
      ],
    },
    session: {
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
    },
    teamMember: {
      team: [
        {
          sourceField: ["teamId"],
          destField: ["id"],
          destSchema: "team",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "user",
          cardinality: "one",
        },
      ],
    },
    team: {
      members: [
        {
          sourceField: ["id"],
          destField: ["teamId"],
          destSchema: "teamMember",
          cardinality: "many",
        },
      ],
      projects: [
        {
          sourceField: ["id"],
          destField: ["teamId"],
          destSchema: "project",
          cardinality: "many",
        },
      ],
      issues: [
        {
          sourceField: ["id"],
          destField: ["teamId"],
          destSchema: "issue",
          cardinality: "many",
        },
      ],
      issueStatuses: [
        {
          sourceField: ["id"],
          destField: ["teamId"],
          destSchema: "issueStatus",
          cardinality: "many",
        },
      ],
      issuePriorities: [
        {
          sourceField: ["id"],
          destField: ["teamId"],
          destSchema: "issuePriority",
          cardinality: "many",
        },
      ],
      issueLabels: [
        {
          sourceField: ["id"],
          destField: ["teamId"],
          destSchema: "issueLabel",
          cardinality: "many",
        },
      ],
    },
    user: {
      sessions: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "session",
          cardinality: "many",
        },
      ],
      accounts: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "account",
          cardinality: "many",
        },
      ],
      teamMemberships: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "teamMember",
          cardinality: "many",
        },
      ],
      createdIssues: [
        {
          sourceField: ["id"],
          destField: ["creatorId"],
          destSchema: "issue",
          cardinality: "many",
        },
      ],
      assignedIssues: [
        {
          sourceField: ["id"],
          destField: ["assigneeId"],
          destSchema: "issue",
          cardinality: "many",
        },
      ],
      ledProjects: [
        {
          sourceField: ["id"],
          destField: ["leadId"],
          destSchema: "project",
          cardinality: "many",
        },
      ],
      issueComments: [
        {
          sourceField: ["id"],
          destField: ["authorId"],
          destSchema: "issueComment",
          cardinality: "many",
        },
      ],
    },
  },
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
