/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookEventTypeIdRouteImport } from './routes/book/$eventTypeId'
import { ServerRoute as ApiQueryServerRouteImport } from './routes/api/query'
import { ServerRoute as ApiMutateServerRouteImport } from './routes/api/mutate'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookEventTypeIdRoute = BookEventTypeIdRouteImport.update({
  id: '/book/$eventTypeId',
  path: '/book/$eventTypeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryServerRoute = ApiQueryServerRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMutateServerRoute = ApiMutateServerRouteImport.update({
  id: '/api/mutate',
  path: '/api/mutate',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/book/$eventTypeId': typeof BookEventTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/book/$eventTypeId': typeof BookEventTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/book/$eventTypeId': typeof BookEventTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/availability'
    | '/bookings'
    | '/login'
    | '/book/$eventTypeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/availability' | '/bookings' | '/login' | '/book/$eventTypeId'
  id:
    | '__root__'
    | '/'
    | '/availability'
    | '/bookings'
    | '/login'
    | '/book/$eventTypeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BookingsRoute: typeof BookingsRoute
  LoginRoute: typeof LoginRoute
  BookEventTypeIdRoute: typeof BookEventTypeIdRoute
}
export interface FileServerRoutesByFullPath {
  '/api/mutate': typeof ApiMutateServerRoute
  '/api/query': typeof ApiQueryServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/mutate': typeof ApiMutateServerRoute
  '/api/query': typeof ApiQueryServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/mutate': typeof ApiMutateServerRoute
  '/api/query': typeof ApiQueryServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/mutate' | '/api/query' | '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/mutate' | '/api/query' | '/api/auth/$'
  id: '__root__' | '/api/mutate' | '/api/query' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiMutateServerRoute: typeof ApiMutateServerRoute
  ApiQueryServerRoute: typeof ApiQueryServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$eventTypeId': {
      id: '/book/$eventTypeId'
      path: '/book/$eventTypeId'
      fullPath: '/book/$eventTypeId'
      preLoaderRoute: typeof BookEventTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/mutate': {
      id: '/api/mutate'
      path: '/api/mutate'
      fullPath: '/api/mutate'
      preLoaderRoute: typeof ApiMutateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvailabilityRoute: AvailabilityRoute,
  BookingsRoute: BookingsRoute,
  LoginRoute: LoginRoute,
  BookEventTypeIdRoute: BookEventTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiMutateServerRoute: ApiMutateServerRoute,
  ApiQueryServerRoute: ApiQueryServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
